const peoplesEmojies = [
  { data: '😀', aliases: ['grinning'] },
  { data: '😁', aliases: ['grin'] },
  { data: '😆', aliases: ['laughing', 'satisfied'] },
  { data: '😅', aliases: ['sweat_smile'] },
  { data: '😂', aliases: ['joy'] },
  { data: '🤣', aliases: ['rofl'] },
  { data: '😌', aliases: ['relaxed'] },
  { data: '😊', aliases: ['blush'] },
  { data: '😇', aliases: ['innocent'] },
  { data: '🙂', aliases: ['slightly_smiling_face'] },
  { data: '🙃', aliases: ['upside_down_face'] },
  { data: '😉', aliases: ['wink'] },
  { data: '😌', aliases: ['relieved'] },
  { data: '😍', aliases: ['heart_eyes'] },
  { data: '😘', aliases: ['kissing_heart'] },
  { data: '😗', aliases: ['kissing'] },
  { data: '😙', aliases: ['kissing_smiling_eyes'] },
  { data: '😚', aliases: ['kissing_closed_eyes'] },
  { data: '😋', aliases: ['yum'] },
  { data: '😜', aliases: ['stuck_out_tongue_winking_eye'] },
  { data: '😝', aliases: ['stuck_out_tongue_closed_eyes'] },
  { data: '😛', aliases: ['stuck_out_tongue'] },
  { data: '🤑', aliases: ['money_mouth_face'] },
  { data: '🤗', aliases: ['hugs'] },
  { data: '🤓', aliases: ['nerd_face'] },
  { data: '😎', aliases: ['sunglasses'] },
  { data: '🤡', aliases: ['clown_face'] },
  { data: '🤠', aliases: ['cowboy_hat_face'] },
  { data: '😏', aliases: ['smirk'] },
  { data: '😒', aliases: ['unamused'] },
  { data: '😞', aliases: ['disappointed'] },
  { data: '😔', aliases: ['pensive'] },
  { data: '😟', aliases: ['worried'] },
  { data: '😕', aliases: ['confused'] },
  { data: '🙁', aliases: ['slightly_frowning_face'] },
  { data: '☹️', aliases: ['frowning_face'] },
  { data: '😣', aliases: ['persevere'] },
  { data: '😖', aliases: ['confounded'] },
  { data: '😫', aliases: ['tired_face'] },
  { data: '😩', aliases: ['weary'] },
  { data: '😤', aliases: ['triumph'] },
  { data: '😠', aliases: ['angry'] },
  { data: '😡', aliases: ['rage', 'pout'] },
  { data: '😶', aliases: ['no_mouth'] },
  { data: '😐', aliases: ['neutral_face'] },
  { data: '😑', aliases: ['expressionless'] },
  { data: '😯', aliases: ['hushed'] },
  { data: '😦', aliases: ['frowning'] },
  { data: '😧', aliases: ['anguished'] },
  { data: '😮', aliases: ['open_mouth'] },
  { data: '😲', aliases: ['astonished'] },
  { data: '😵', aliases: ['dizzy_face'] },
  { data: '😳', aliases: ['flushed'] },
  { data: '😱', aliases: ['scream'] },
  { data: '😨', aliases: ['fearful'] },
  { data: '😰', aliases: ['cold_sweat'] },
  { data: '😢', aliases: ['cry'] },
  { data: '😥', aliases: ['disappointed_relieved'] },
  { data: '🤤', aliases: ['drooling_face'] },
  { data: '😭', aliases: ['sob'] },
  { data: '😓', aliases: ['sweat'] },
  { data: '😪', aliases: ['sleepy'] },
  { data: '😴', aliases: ['sleeping'] },
  { data: '🙄', aliases: ['roll_eyes'] },
  { data: '🤔', aliases: ['thinking'] },
  { data: '🤥', aliases: ['lying_face'] },
  { data: '😬', aliases: ['grimacing'] },
  { data: '🤐', aliases: ['zipper_mouth_face'] },
  { data: '🤢', aliases: ['nauseated_face'] },
  { data: '🤧', aliases: ['sneezing_face'] },
  { data: '😷', aliases: ['mask'] },
  { data: '🤒', aliases: ['face_with_thermometer'] },
  { data: '🤕', aliases: ['face_with_head_bandage'] },
  { data: '😈', aliases: ['smiling_imp'] },
  { data: '👿', aliases: ['imp'] },
  { data: '👹', aliases: ['japanese_ogre'] },
  { data: '👺', aliases: ['japanese_goblin'] },
  { data: '💩', aliases: ['hankey', 'poop', 'shit'] },
  { data: '👻', aliases: ['ghost'] },
  { data: '💀', aliases: ['skull'] },
  { data: '☠️', aliases: ['skull_and_crossbones'] },
  { data: '👽', aliases: ['alien'] },
  { data: '👾', aliases: ['space_invader'] },
  { data: '🤖', aliases: ['robot'] },
  { data: '🎃', aliases: ['jack_o_lantern'] },
  { data: '😺', aliases: ['smiley_cat'] },
  { data: '😸', aliases: ['smile_cat'] },
  { data: '😹', aliases: ['joy_cat'] },
  { data: '😻', aliases: ['heart_eyes_cat'] },
  { data: '😼', aliases: ['smirk_cat'] },
  { data: '😽', aliases: ['kissing_cat'] },
  { data: '🙀', aliases: ['scream_cat'] },
  { data: '😿', aliases: ['crying_cat_face'] },
  { data: '😾', aliases: ['pouting_cat'] },
  { data: '👐', aliases: ['open_hands'] },
  { data: '🙌', aliases: ['raised_hands'] },
  { data: '👏', aliases: ['clap'] },
  { data: '🙏', aliases: ['pray'] },
  { data: '🤝', aliases: ['handshake'] },
  { data: '👍', aliases: ['+1', 'thumbsup'] },
  { data: '👎', aliases: ['-1', 'thumbsdown'] },
  { data: '👊', aliases: ['fist_oncoming', 'facepunch', 'punch'] },
  { data: '✊', aliases: ['fist_raised', 'fist'] },
  { data: '🤛', aliases: ['fist_left'] },
  { data: '🤜', aliases: ['fist_right'] },
  { data: '🤞', aliases: ['crossed_fingers'] },
  { data: '✌️', aliases: ['v'] },
  { data: '🤘', aliases: ['metal'] },
  { data: '👌', aliases: ['ok_hand'] },
  { data: '👈', aliases: ['point_left'] },
  { data: '👉', aliases: ['point_right'] },
  { data: '👆', aliases: ['point_up_2'] },
  { data: '👇', aliases: ['point_down'] },
  { data: '☝️', aliases: ['point_up'] },
  { data: '✋', aliases: ['hand', 'raised_hand'] },
  { data: '🤚', aliases: ['raised_back_of_hand'] },
  { data: '🖐', aliases: ['raised_hand_with_fingers_splayed'] },
  { data: '🖖', aliases: ['vulcan_salute'] },
  { data: '👋', aliases: ['wave'] },
  { data: '🤙', aliases: ['call_me_hand'] },
  { data: '💪', aliases: ['muscle'] },
  { data: '🖕', aliases: ['middle_finger', 'fu'] },
  { data: '✍️', aliases: ['writing_hand'] },
  { data: '🤳', aliases: ['selfie'] },
  { data: '💅', aliases: ['nail_care'] },
  { data: '💍', aliases: ['ring'] },
  { data: '💄', aliases: ['lipstick'] },
  { data: '💋', aliases: ['kiss'] },
  { data: '👄', aliases: ['lips'] },
  { data: '👅', aliases: ['tongue'] },
  { data: '👂', aliases: ['ear'] },
  { data: '👃', aliases: ['nose'] },
  { data: '👣', aliases: ['footprints'] },
  { data: '👁', aliases: ['eye'] },
  { data: '👀', aliases: ['eyes'] },
  { data: '🗣', aliases: ['speaking_head'] },
  { data: '👤', aliases: ['bust_in_silhouette'] },
  { data: '👥', aliases: ['busts_in_silhouette'] },
  { data: '👶', aliases: ['baby'] },
  { data: '👦', aliases: ['boy'] },
  { data: '👧', aliases: ['girl'] },
  { data: '👨', aliases: ['man'] },
  { data: '👩', aliases: ['woman'] },
  { data: '👱‍♀', aliases: ['blonde_woman'] },
  { data: '👱', aliases: ['blonde_man', 'person_with_blond_hair'] },
  { data: '👴', aliases: ['older_man'] },
  { data: '👵', aliases: ['older_woman'] },
  { data: '👲', aliases: ['man_with_gua_pi_mao'] },
  { data: '👳‍♀', aliases: ['woman_with_turban'] },
  { data: '👳', aliases: ['man_with_turban'] },
  { data: '👮‍♀', aliases: ['policewoman'] },
  { data: '👮', aliases: ['policeman', 'cop'] },
  { data: '👷‍♀', aliases: ['construction_worker_woman'] },
  { data: '👷', aliases: ['construction_worker_man', 'construction_worker'] },
  { data: '💂‍♀', aliases: ['guardswoman'] },
  { data: '💂', aliases: ['guardsman'] },
  { data: '👩‍⚕', aliases: ['woman_health_worker'] },
  { data: '👨‍⚕', aliases: ['man_health_worker'] },
  { data: '👩‍🌾', aliases: ['woman_farmer'] },
  { data: '👨‍🌾', aliases: ['man_farmer'] },
  { data: '👩‍🍳', aliases: ['woman_cook'] },
  { data: '👨‍🍳', aliases: ['man_cook'] },
  { data: '👩‍🎓', aliases: ['woman_student'] },
  { data: '👨‍🎓', aliases: ['man_student'] },
  { data: '👩‍🎤', aliases: ['woman_singer'] },
  { data: '👨‍🎤', aliases: ['man_singer'] },
  { data: '👩‍🏫', aliases: ['woman_teacher'] },
  { data: '👨‍🏫', aliases: ['man_teacher'] },
  { data: '👩‍🏭', aliases: ['woman_factory_worker'] },
  { data: '👨‍🏭', aliases: ['man_factory_worker'] },
  { data: '👩‍💻', aliases: ['woman_technologist'] },
  { data: '👨‍💻', aliases: ['man_technologist'] },
  { data: '👩‍💼', aliases: ['woman_office_worker'] },
  { data: '👨‍💼', aliases: ['man_office_worker'] },
  { data: '👩‍🔧', aliases: ['woman_mechanic'] },
  { data: '👨‍🔧', aliases: ['man_mechanic'] },
  { data: '👩‍🔬', aliases: ['woman_scientist'] },
  { data: '👨‍🔬', aliases: ['man_scientist'] },
  { data: '👩‍🎨', aliases: ['woman_artist'] },
  { data: '👨‍🎨', aliases: ['man_artist'] },
  { data: '👩‍🚒', aliases: ['woman_firefighter'] },
  { data: '👨‍🚒', aliases: ['man_firefighter'] },
  { data: '👩‍🚀', aliases: ['woman_astronaut'] },
  { data: '👨‍🚀', aliases: ['man_astronaut'] },
  { data: '🤶', aliases: ['mrs_claus'] },
  { data: '🎅', aliases: ['santa'] },
  { data: '👸', aliases: ['princess'] },
  { data: '🤴', aliases: ['prince'] },
  { data: '👰', aliases: ['bride_with_veil'] },
  { data: '🤵', aliases: ['man_in_tuxedo'] },
  { data: '👼', aliases: ['angel'] },
  { data: '🤰', aliases: ['pregnant_woman'] },
  { data: '🙇‍♀', aliases: ['bowing_woman'] },
  { data: '🙇', aliases: ['bowing_man', 'bow'] },
  { data: '💁', aliases: ['tipping_hand_woman', 'information_desk_person', 'sassy_woman'] },
  { data: '💁‍♂', aliases: ['tipping_hand_man', 'sassy_man'] },
  { data: '🙅', aliases: ['no_good_woman', 'no_good', 'ng_woman'] },
  { data: '🙅‍♂', aliases: ['no_good_man', 'ng_man'] },
  { data: '🙆', aliases: ['ok_woman'] },
  { data: '🙆‍♂', aliases: ['ok_man'] },
  { data: '🙋', aliases: ['raising_hand_woman', 'raising_hand'] },
  { data: '🙋‍♂', aliases: ['raising_hand_man'] },
  { data: '🤦‍♀', aliases: ['woman_facepalming'] },
  { data: '🤦‍♂', aliases: ['man_facepalming'] },
  { data: '🤷‍♀', aliases: ['woman_shrugging'] },
  { data: '🤷‍♂', aliases: ['man_shrugging'] },
  { data: '🙎', aliases: ['pouting_woman', 'person_with_pouting_face'] },
  { data: '🙎‍♂', aliases: ['pouting_man'] },
  { data: '🙍', aliases: ['frowning_woman', 'person_frowning'] },
  { data: '🙍‍♂', aliases: ['frowning_man'] },
  { data: '💇', aliases: ['haircut_woman', 'haircut'] },
  { data: '💇‍♂', aliases: ['haircut_man'] },
  { data: '💆', aliases: ['massage_woman', 'massage'] },
  { data: '💆‍♂', aliases: ['massage_man'] },
  { data: '🕴', aliases: ['business_suit_levitating'] },
  { data: '💃', aliases: ['dancer'] },
  { data: '🕺', aliases: ['man_dancing'] },
  { data: '👯', aliases: ['dancing_women', 'dancers'] },
  { data: '👯‍♂', aliases: ['dancing_men'] },
  { data: '🚶‍♀', aliases: ['walking_woman'] },
  { data: '🚶', aliases: ['walking_man', 'walking'] },
  { data: '🏃‍♀', aliases: ['running_woman'] },
  { data: '🏃', aliases: ['running_man', 'runner', 'running'] },
  { data: '👫', aliases: ['couple'] },
  { data: '👭', aliases: ['two_women_holding_hands'] },
  { data: '👬', aliases: ['two_men_holding_hands'] },
  { data: '💑', aliases: ['couple_with_heart_woman_man', 'couple_with_heart'] },
  { data: '👩‍❤️‍👩', aliases: ['couple_with_heart_woman_woman'] },
  { data: '👨‍❤️‍👨', aliases: ['couple_with_heart_man_man'] },
  { data: '💏', aliases: ['couplekiss_man_woman'] },
  { data: '👩‍❤️‍💋‍👩', aliases: ['couplekiss_woman_woman'] },
  { data: '👨‍❤️‍💋‍👨', aliases: ['couplekiss_man_man'] },
  { data: '👪', aliases: ['family_man_woman_boy', 'family'] },
  { data: '👨‍👩‍👧', aliases: ['family_man_woman_girl'] },
  { data: '👨‍👩‍👧‍👦', aliases: ['family_man_woman_girl_boy'] },
  { data: '👨‍👩‍👦‍👦', aliases: ['family_man_woman_boy_boy'] },
  { data: '👨‍👩‍👧‍👧', aliases: ['family_man_woman_girl_girl'] },
  { data: '👩‍👩‍👦', aliases: ['family_woman_woman_boy'] },
  { data: '👩‍👩‍👧', aliases: ['family_woman_woman_girl'] },
  { data: '👩‍👩‍👧‍👦', aliases: ['family_woman_woman_girl_boy'] },
  { data: '👩‍👩‍👦‍👦', aliases: ['family_woman_woman_boy_boy'] },
  { data: '👩‍👩‍👧‍👧', aliases: ['family_woman_woman_girl_girl'] },
  { data: '👨‍👨‍👦', aliases: ['family_man_man_boy'] },
  { data: '👨‍👨‍👧', aliases: ['family_man_man_girl'] },
  { data: '👨‍👨‍👧‍👦', aliases: ['family_man_man_girl_boy'] },
  { data: '👨‍👨‍👦‍👦', aliases: ['family_man_man_boy_boy'] },
  { data: '👨‍👨‍👧‍👧', aliases: ['family_man_man_girl_girl'] },
  { data: '👩‍👦', aliases: ['family_woman_boy'] },
  { data: '👩‍👧', aliases: ['family_woman_girl'] },
  { data: '👩‍👧‍👦', aliases: ['family_woman_girl_boy'] },
  { data: '👩‍👦‍👦', aliases: ['family_woman_boy_boy'] },
  { data: '👩‍👧‍👧', aliases: ['family_woman_girl_girl'] },
  { data: '👨‍👦', aliases: ['family_man_boy'] },
  { data: '👨‍👧', aliases: ['family_man_girl'] },
  { data: '👨‍👧‍👦', aliases: ['family_man_girl_boy'] },
  { data: '👨‍👦‍👦', aliases: ['family_man_boy_boy'] },
  { data: '👨‍👧‍👧', aliases: ['family_man_girl_girl'] },
  { data: '👚', aliases: ['womans_clothes'] },
  { data: '👕', aliases: ['shirt', 'tshirt'] },
  { data: '👖', aliases: ['jeans'] },
  { data: '👔', aliases: ['necktie'] },
  { data: '👗', aliases: ['dress'] },
  { data: '👙', aliases: ['bikini'] },
  { data: '👘', aliases: ['kimono'] },
  { data: '👠', aliases: ['high_heel'] },
  { data: '👡', aliases: ['sandal'] },
  { data: '👢', aliases: ['boot'] },
  { data: '👞', aliases: ['mans_shoe', 'shoe'] },
  { data: '👟', aliases: ['athletic_shoe'] },
  { data: '👒', aliases: ['womans_hat'] },
  { data: '🎩', aliases: ['tophat'] },
  { data: '🎓', aliases: ['mortar_board'] },
  { data: '👑', aliases: ['crown'] },
  { data: '⛑', aliases: ['rescue_worker_helmet'] },
  { data: '🎒', aliases: ['school_satchel'] },
  { data: '👝', aliases: ['pouch'] },
  { data: '👛', aliases: ['purse'] },
  { data: '👜', aliases: ['handbag'] },
  { data: '💼', aliases: ['briefcase'] },
  { data: '👓', aliases: ['eyeglasses'] },
  { data: '🕶', aliases: ['dark_sunglasses'] },
  { data: '🌂', aliases: ['closed_umbrella'] },
  { data: '☂️', aliases: ['open_umbrella'] }
]

const foodsEmojies = [
  { data: '🍏', aliases: ['green_apple'] },
  { data: '🍎', aliases: ['apple'] },
  { data: '🍐', aliases: ['pear'] },
  { data: '🍊', aliases: ['tangerine', 'orange', 'mandarin'] },
  { data: '🍋', aliases: ['lemon'] },
  { data: '🍌', aliases: ['banana'] },
  { data: '🍉', aliases: ['watermelon'] },
  { data: '🍇', aliases: ['grapes'] },
  { data: '🍓', aliases: ['strawberry'] },
  { data: '🍈', aliases: ['melon'] },
  { data: '🍒', aliases: ['cherries'] },
  { data: '🍑', aliases: ['peach'] },
  { data: '🍍', aliases: ['pineapple'] },
  { data: '🥝', aliases: ['kiwi_fruit'] },
  { data: '🥑', aliases: ['avocado'] },
  { data: '🍅', aliases: ['tomato'] },
  { data: '🍆', aliases: ['eggplant'] },
  { data: '🥒', aliases: ['cucumber'] },
  { data: '🥕', aliases: ['carrot'] },
  { data: '🌽', aliases: ['corn'] },
  { data: '🌶', aliases: ['hot_pepper'] },
  { data: '🥔', aliases: ['potato'] },
  { data: '🍠', aliases: ['sweet_potato'] },
  { data: '🌰', aliases: ['chestnut'] },
  { data: '🥜', aliases: ['peanuts'] },
  { data: '🍯', aliases: ['honey_pot'] },
  { data: '🥐', aliases: ['croissant'] },
  { data: '🍞', aliases: ['bread'] },
  { data: '🥖', aliases: ['baguette_bread'] },
  { data: '🧀', aliases: ['cheese'] },
  { data: '🥚', aliases: ['egg'] },
  { data: '🍳', aliases: ['fried_egg'] },
  { data: '🥓', aliases: ['bacon'] },
  { data: '🥞', aliases: ['pancakes'] },
  { data: '🍤', aliases: ['fried_shrimp'] },
  { data: '🍗', aliases: ['poultry_leg'] },
  { data: '🍖', aliases: ['meat_on_bone'] },
  { data: '🍕', aliases: ['pizza'] },
  { data: '🌭', aliases: ['hotdog'] },
  { data: '🍔', aliases: ['hamburger'] },
  { data: '🍟', aliases: ['fries'] },
  { data: '🥙', aliases: ['stuffed_flatbread'] },
  { data: '🌮', aliases: ['taco'] },
  { data: '🌯', aliases: ['burrito'] },
  { data: '🥗', aliases: ['green_salad'] },
  { data: '🥘', aliases: ['shallow_pan_of_food'] },
  { data: '🍝', aliases: ['spaghetti'] },
  { data: '🍜', aliases: ['ramen'] },
  { data: '🍲', aliases: ['stew'] },
  { data: '🍥', aliases: ['fish_cake'] },
  { data: '🍣', aliases: ['sushi'] },
  { data: '🍱', aliases: ['bento'] },
  { data: '🍛', aliases: ['curry'] },
  { data: '🍚', aliases: ['rice'] },
  { data: '🍙', aliases: ['rice_ball'] },
  { data: '🍘', aliases: ['rice_cracker'] },
  { data: '🍢', aliases: ['oden'] },
  { data: '🍡', aliases: ['dango'] },
  { data: '🍧', aliases: ['shaved_ice'] },
  { data: '🍨', aliases: ['ice_cream'] },
  { data: '🍦', aliases: ['icecream'] },
  { data: '🍰', aliases: ['cake'] },
  { data: '🎂', aliases: ['birthday'] },
  { data: '🍮', aliases: ['custard'] },
  { data: '🍭', aliases: ['lollipop'] },
  { data: '🍬', aliases: ['candy'] },
  { data: '🍫', aliases: ['chocolate_bar'] },
  { data: '🍿', aliases: ['popcorn'] },
  { data: '🍩', aliases: ['doughnut'] },
  { data: '🍪', aliases: ['cookie'] },
  { data: '🥛', aliases: ['milk_glass'] },
  { data: '🍼', aliases: ['baby_bottle'] },
  { data: '☕️', aliases: ['coffee'] },
  { data: '🍵', aliases: ['tea'] },
  { data: '🍶', aliases: ['sake'] },
  { data: '🍺', aliases: ['beer'] },
  { data: '🍻', aliases: ['beers'] },
  { data: '🥂', aliases: ['clinking_glasses'] },
  { data: '🍷', aliases: ['wine_glass'] },
  { data: '🥃', aliases: ['tumbler_glass'] },
  { data: '🍸', aliases: ['cocktail'] },
  { data: '🍹', aliases: ['tropical_drink'] },
  { data: '🍾', aliases: ['champagne'] },
  { data: '🥄', aliases: ['spoon'] },
  { data: '🍴', aliases: ['fork_and_knife'] },
  { data: '🍽', aliases: ['plate_with_cutlery'] }
]

export const mapEmojies = {
  'peoples': peoplesEmojies,
  'foods': foodsEmojies
}
